---
title: "stage_10_3_biotime_mhws"
author: "Shahar Chaikin"
date: "2025-10-01"
output: html_document
---

library
```{r}
library(tidyverse)
```

Load data
#fixed baseline
Abundance
```{r}
biotime_cleaned_abundance=read_rds("annual_n_ratio_biotime.rds") #%>% 
  #left_join(read.csv("nis_native_harmo.csv"),by="species")
#MHWs
mhws_annual_fbl=read_rds("annual_c_int.rds") %>% 
  filter(h3_id%in%biotime_cleaned_abundance$h3_id %>% unique)

#add MHWs to medits
biotime_mhw_n_fbl=biotime_cleaned_abundance %>% 
  left_join(mhws_annual_fbl %>% 
              select(h3_id,
                     year_of_mhw=year_of_mhws,
                     annual_c_int),
            by=c("h3_id","year_of_mhw"))

#write_rds(biotime_mhw_n_fbl,"biotime_mhw_n_fbl.rds")
```
#Detrended

Abundance
```{r}
biotime_cleaned_abundance=read_rds("annual_n_ratio_biotime.rds") #%>% 
 # left_join(read.csv("nis_native_harmo.csv"),by="species")
#MHWs
mhws_annual_dt=read_rds("annual_c_int_dt.rds") %>% 
  filter(h3_id%in%biotime_cleaned_abundance$h3_id %>% unique)

#add MHWs to medits
biotime_mhw_n=biotime_cleaned_abundance %>% 
  left_join(mhws_annual_dt %>% 
              select(h3_id,
                     year_of_mhw=year_of_mhws,
                     annual_c_int),
            by=c("h3_id","year_of_mhw"))

#write_rds(biotime_mhw_n,"biotime_mhw_n_dt.rds")
```